---
- hosts: localhost

  tasks:
  - name: install openjdk-8-jdk
    become: yes
    become_method: sudo
    apt:
      name: openjdk-8-jdk
    register: resutt
  - debug:
      var: result

  - name: java version
    shell: java -version
    register: result
  - debug:
      var: result

# due to ubuntu 18.04 or openjdk 9 and later the keystore in /etc/ssl/certs/java/cacerts does not work ("InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty")
# solution: rm cacerts and update
# source: https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1739631
  - name: update java keystore
    become: yes
    become_method: sudo
    shell: rm /etc/ssl/certs/java/cacerts;update-ca-certificates -f
    register: result
  - debug:
      var: result

  - name: set JAVA_HOME in .bashrc
    shell: grep -q -F 'JAVA_HOME=' $HOME/.bashrc || echo 'JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' >> $HOME/.bashrc;grep -q -F 'export JAVA_HOME' $HOME/.bashrc || echo 'export JAVA_HOME' >> $HOME/.bashrc
    register: result
  - debug:
      var: result

  - name: set PATH in .bashrc
    shell: grep -q -F 'PATH=$PATH' $HOME/.bashrc || echo 'PATH=$PATH:$JAVA_HOME:$HOME/data/040_development/100_lexoffice/grld-provisioning/vagrant-multihost/scripts:$HOME/data/040_development/rerun' >> $HOME/.bashrc;grep -q -F 'export PATH' $HOME/.bashrc || echo 'export PATH' >> $HOME/.bashrc
    register: result
  - debug:
      var: result

  - name: create /etc/profile.d/export-histtime.sh
    become: yes
    become_method: sudo
    shell: echo "export HISTTIMEFORMAT='%Y%m%d %T'" > /etc/profile.d/export-histtime.sh
    register: result
  - debug:
      var: result

  - name: unlimited bash history size
    shell: sed -i 's/HISTSIZE=1000/HISTSIZE=/g' $HOME/.bashrc
    register: result
  - debug:
      var: result

  - name: unlimited bash history file size
    shell: sed -i 's/HISTFILESIZE=2000/HISTFILESIZE=/g' $HOME/.bashrc
    register: result
  - debug:
      var: result

  - name: apt update
    become: yes
    become_method: sudo
    apt: 
      update_cache: yes
    register: result
  - debug: var=result

  - name: chmod 700 $HOME/.ssh/id_rsa
    shell: ls -al $HOME/.ssh/id_rsa;chmod 700 $HOME/.ssh/id_rsa;ls -al $HOME/.ssh/id_rsa
    register: result
  - debug:
      var: result

#  - name: ssh-add for bitbucket
#    shell: ssh-add $HOME/.ssh/id_rsa
#    register: result
#  - debug:
#      var: result

  - name: install libgxps-utils for xps2pdf conversion
    become: yes
    become_method: sudo
    apt:
      name: libgxps-utils
    register: result
  - debug:
      var: result

  - name: install curl
    become: yes
    become_method: sudo
    apt:
      name: curl
    register: result
  - debug:
      var: result

  - name: install git
    become: yes
    become_method: sudo
    apt: 
      name: git
      state: present
    register: result
  - debug: var=result

  - name: git user.email
    shell: git config --global user.email tai.truong@haufe-lexware.net
    register: result
  - debug:
      var: result

  - name: git user.name
    shell: git config --global user.name taitruong2
    register: result
  - debug:
      var: result

  - name: sudo deb http://repo.vivaldi.com/stable/deb/ stable main > /etc/apt/sources.list.d/vivaldi.list
    shell: echo "echo deb http://repo.vivaldi.com/stable/deb/ stable main > /etc/apt/sources.list.d/vivaldi.list" | sudo sh; ls /etc/apt/sources.list.d/
    register: result
  - debug:
      var: result

  - name: curl http://repo.vivaldi.com/stable/linux_signing_key.pub | sudo apt-key add -
    shell: curl http://repo.vivaldi.com/stable/linux_signing_key.pub | sudo apt-key add -
    register: result
  - debug:
      var: result

  - name: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1397BC53640DB551
    become: yes
    become_method: sudo
    shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1397BC53640DB551
    register: result
  - debug:
      var: result

  - name: apt update
    become: yes
    become_method: sudo
    apt:
      update_cache: yes
    register: result
  - debug: var=result

  - name: install vivaldi-stable
    become: yes
    become_method: sudo
    apt:
      name: vivaldi-stable
    register: result
  - debug:
      var: result

  - name: install pgadmin3
    become: yes
    become_method: sudo
    apt:
      name: pgadmin3
    register: result
  - debug:
      var: result

  - name: add idea repository
    become: yes
    apt_repository: repo="ppa:mmk2410/intellij-idea"
    register: result
  - debug:
      var: result

  - name: install idea ultimate
    become: yes
    become_method: sudo
    apt:
      name: intellij-idea-ultimate
    register: result
  - debug:
      var: result

  - name: install virtual box
    become: yes
    become_method: sudo
    apt:
      name: virtualbox
    register: result
  - debug:
      var: result

# ubuntu 18.04, June 5th, 2018: vbguest needs latest vagrant
# source: https://github.com/dotless-de/vagrant-vbguest/issues/292
  - name: install vagrant
    become: yes
    become_method: sudo
    shell: wget -c https://releases.hashicorp.com/vagrant/2.1.1/vagrant_2.1.1_x86_64.deb;dpkg -i vagrant_2.1.1_x86_64.deb; rm vagrant_2.1.1_x86_64.deb
    register: result
  - debug:
      var: result

  - name: vagrant plugin install vagrant-vbguest
    shell: vagrant plugin install vagrant-vbguest
    register: result
  - debug:
      var: result

  - name: vagrant plugin install vagrant-hosts
    shell: vagrant plugin install vagrant-hosts
    register: result
  - debug:
      var: result

  - name: apt-key adv --keyserver keyserver.ubuntu.com --recv 68576280
    become: yes
    become_method: sudo
    shell: apt-key adv --keyserver keyserver.ubuntu.com --recv 68576280
    register: result
  - debug:
      var: result

  - name: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    become: yes
    become_method: sudo
    shell: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    register: result
  - debug:
      var: result

  - name: apt update
    become: yes
    become_method: sudo
    apt:
      update_cache: yes
    register: result
  - debug: var=result

  - name: install nodejs
    become: yes
    become_method: sudo
    apt:
      name: nodejs
    register: result
  - debug:
      var: result

  - name: npm install -g grunt-cli
    become: yes
    become_method: sudo
    shell: npm install -g grunt-cli
    register: result
  - debug:
      var: result

  - name: install maven
    become: yes
    become_method: sudo
    apt:
      name: maven
    register: result
  - debug:
      var: result

  - name: add gradle repository
    become: yes
    apt_repository: repo="ppa:cwchien/gradle"
    register: result
  - debug:
      var: result

  - name: apt update
    become: yes
    become_method: sudo
    apt:
      update_cache: yes
    register: result
  - debug: var=result

  - name: install gradle
    become: yes
    become_method: sudo
    apt:
      name: gradle
    register: result
  - debug:
      var: result

  - name: echo "grldS3BucketName=grld-dev-tai-truong" > $HOME/.gradle/gradle.properties
    shell: echo "grldS3BucketName=grld-dev-tai-truong" > $HOME/.gradle/gradle.properties
    register: result
  - debug:
      var: result

  - name: echo "artifactoryUsername=tai.truong" >> $HOME/.gradle/gradle.properties
    shell: echo "artifactoryUsername=tai.truong" >> $HOME/.gradle/gradle.properties
    register: result
  - debug:
      var: result

  - name: echo "artifactoryPassword=test" >> $HOME/.gradle/gradle.properties
    shell: echo "artifactoryPassword=testtest" >> $HOME/.gradle/gradle.properties
    register: result
  - debug:
      var: result

  - name: less $HOME/.gradle/gradle.properties
    shell: less $HOME/.gradle/gradle.properties
    register: result
  - debug:
      var: result

  - name: install pinta
    become: yes
    become_method: sudo
    apt:
      name: pinta
    register: result
  - debug:
      var: result

  - name: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0DF731E45CE24F27EEEB1450EFDC8610341D9410 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
    become: yes
    become_method: sudo
    shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0DF731E45CE24F27EEEB1450EFDC8610341D9410 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
    register: result
  - debug:
      var: result

  - name: echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
    shell: echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
    register: result
  - debug:
      var: result

  - name: apt update
    become: yes
    become_method: sudo
    apt:
      update_cache: yes
    register: result
  - debug: var=result

  - name: install spotify-client
    become: yes
    become_method: sudo
    apt:
      name: spotify-client
    register: result
  - debug:
      var: result

  - name: apt autoremove
    become: yes
    become_method: sudo
    apt:
      autoremove: yes
    register: result
  - debug:
      var: result

# ------------- lexoffice repo configuration -------------
  - name: install awscli
    become: yes
    become_method: sudo
    apt:
      name: awscli
    register: result
  - debug:
      var: result

  - name: cp grld-provisioning/vagrant-multihost/scripts/environment.sh
    shell: cp $HOME/data/040_development/100_lexoffice/grld-provisioning/vagrant-multihost/scripts/_environment.sh $HOME/data/040_development/100_lexoffice/grld-provisioning/vagrant-multihost/scripts/environment.sh
    register: result
  - debug:
      var: result

  - name: REPO_DIR - grld-provisioning/vagrant-multihost/scripts/environment.sh
    shell: sed -i 's/.*export REPO_DIR=.*/export REPO_DIR=$HOME\/data\/040_development\/100_lexoffice/g' /home/tt/data/040_development/100_lexoffice/grld-provisioning/vagrant-multihost/scripts/environment.sh
    register: result
  - debug:
      var: result

  - name: cp grld-provisioning/vagrant-multihost/enviroment.rb
    shell: cp $HOME/data/040_development/100_lexoffice/grld-provisioning/vagrant-multihost/_enviroment.rb $HOME/data/040_development/100_lexoffice/grld-provisioning/vagrant-multihost/enviroment.rb
    register: result
  - debug:
      var: result

  - name: REPO_ROOT_FOLDER - grld-provisioning/vagrant-multihost/enviroment.rb
    shell: sed -i 's/.*REPO_ROOT_FOLDER = .*/  REPO_ROOT_FOLDER = '\''\/home\/tt\/data\/040_development\/100_lexoffice'\''/g' $HOME/data/040_development/100_lexoffice/grld-provisioning/vagrant-multihost/enviroment.rb
    register: result
  - debug:
      var: result

  - name: AWS_BUCKET_NAME - grld-provisioning/vagrant-multihost/enviroment.rb
    shell: sed -i 's/.*AWS_BUCKET_NAME = .*/  AWS_BUCKET_NAME = '\''grld-dev-tai-truong'\''/g' $HOME/data/040_development/100_lexoffice/grld-provisioning/vagrant-multihost/enviroment.rb
    register: result
  - debug:
      var: result

  - name: cp .m2/settings.xml
    shell: mkdir $HOME/.m2;cp $HOME/data/040_development/100_lexoffice/grld-provisioning/vagrant-multihost/grld-dev-vagrant/maven/_settings.xml $HOME/.m2/settings.xml
    register: result
  - debug:
      var: result

  - name: set USER - $HOME/.m2/settings.xml
    shell: sed -i 's/<username>.*<\/username>/<username>tai.truong<\/username>/g' $HOME/.m2/settings.xml
    register: result
  - debug:
      var: result

  - name: set PASSWORD - $HOME/.m2/settings.xml
    shell: sed -i 's/<password>.*<\/password>/<password>PASSWORDxxxxxx<\/password>/g' $HOME/.m2/settings.xml
    register: result
  - debug:
      var: result

# --------------------------------------------------------
